services:
  db:
    image: postgres:15
    container_name: hrbot_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aassww2222
      POSTGRES_DB: hrbot
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
